sudo: false
language: elm

script:
  - elm-format --validate src tests examples readme-example
  - cd examples
  - elm make --output=/dev/null
  - cd ../readme-example
  - elm make --output=/dev/null
  - cd ..
  # this line is here to catch type errors until phantom-types is merged into
  # master, at which point it can be replaced by the test script again. :)
  - elm make --docs=/dev/null
  # - npm test
