environment:
  ELM_VERSION: "0.16.0"
  matrix:
  - nodejs_version: "5.0"
  - nodejs_version: "0.12"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION% elm-test
  - npm install

test_script:
  - elm package install --yes
  - cd test
  - elm-test TestRunner.elm
  - npm test

build: off
